# Generated by Django 5.0.7 on 2025-01-06 09:20

import common.enums
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Оплата прошла')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True)),
                ('brief', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка')),
                ('distance', models.IntegerField(verbose_name='Дистанция')),
                ('map_embed_src', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на карту')),
                ('gpx', models.FileField(blank=True, upload_to='gpx', verbose_name='Трек *.gpx')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(null=True, verbose_name='Время старта')),
                ('start_location', models.CharField(max_length=255, null=True, verbose_name='Место старта')),
                ('vk_xref', models.URLField(blank=True, verbose_name='Ссылка ВК')),
                ('rules_doc', models.FileField(blank=True, upload_to='event_rules', verbose_name='Регламент')),
                ('finished', models.BooleanField(default=False, verbose_name='Событие закончено')),
                ('registration_closed', models.BooleanField(default=False, verbose_name='Регистрация закрыта')),
                ('emegrency_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Для печати на номерах', max_length=128, null=True, region=None, verbose_name='Номер телефона для экстренной связи')),
                ('result_qr', models.ImageField(blank=True, help_text='Для печати на номерах', null=True, upload_to='events/results_qr', verbose_name='QR протокола')),
                ('detail_template', models.CharField(default='events/detail.html', max_length=127, verbose_name='Шаблон лэндинга')),
                ('results_template', models.CharField(default='events/results.html', max_length=127, verbose_name='Шаблон протокола')),
                ('hx_payment_template', models.CharField(default='events/hx_payment_info.html', max_length=127, verbose_name='Шаблон платежа')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Cобытия',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_value', models.IntegerField(blank=True, null=True, verbose_name='Сумма к оплате')),
                ('payment_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карты')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='URL для оплаты')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='events/payment_qr', verbose_name='QR для оплаты')),
                ('payment_sbp_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон для оплаты по СБП')),
                ('payment_sbp_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='ФИО для оплаты по СБП')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Время')),
                ('status', models.IntegerField(choices=[(0, 'OK'), (1, 'OTL'), (2, 'DNF'), (3, 'DSQ')], default=common.enums.ResultStatus['OK'], verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
