# Generated by Django 5.0.7 on 2025-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules_doc',
        ),
        migrations.AddField(
            model_name='event',
            name='legend_doc',
            field=models.FileField(blank=True, upload_to='event_rules', verbose_name='Легенда'),
        ),
        migrations.AddField(
            model_name='event',
            name='qualification_txt',
            field=models.TextField(blank=True, verbose_name='Коротко о квалификации'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_txt',
            field=models.TextField(blank=True, verbose_name='Коротко о правилах'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на правила'),
        ),
        migrations.AddField(
            model_name='event',
            name='support_txt',
            field=models.TextField(blank=True, verbose_name='Коротко о поддержке'),
        ),
    ]
