# Generated by Django 5.0.7 on 2025-01-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_result_homologation_alter_application_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('saved', models.DateTimeField(auto_now=True, verbose_name='Дата сохранения')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('distance', models.IntegerField(verbose_name='Расстояние от старта')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
