# Generated by Django 5.0.7 on 2025-01-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'КП', 'verbose_name_plural': 'КП'},
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_value',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='event',
            name='detail_template',
            field=models.CharField(default='events/tus/detail.html', max_length=127, verbose_name='Шаблон лэндинга'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hx_payment_template',
            field=models.CharField(default='events/tus/hx_payment_info.html', max_length=127, verbose_name='Шаблон платежа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='results_template',
            field=models.CharField(default='events/tus/results.html', max_length=127, verbose_name='Шаблон протокола'),
        ),
    ]
