# Generated by Django 5.0.7 on 2025-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_control_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_info',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_qr',
            new_name='qr',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_sbp_name',
            new_name='sbp_name',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_sbp_phone',
            new_name='sbp_phone',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='payment_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя держателя карты'),
        ),
    ]
