# Generated by Django 5.1.4 on 2025-01-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_supportorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_of', to='events.supportorg', verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='EventSupportOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('support_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.supportorg', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Связь "Событие-Организация"',
                'verbose_name_plural': 'Связи "Событие-Организация"',
                'ordering': ('priority', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='support_orgs',
            field=models.ManyToManyField(through='events.EventSupportOrg', to='events.supportorg'),
        ),
    ]
