# Generated by Django 5.1.4 on 2025-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventsupportorg_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsupportorg',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
