# Generated by Django 5.1.4 on 2025-01-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventsupportorg_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsupportorg',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Организация - Событие', 'verbose_name_plural': 'Организации - События'},
        ),
    ]
